apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: game-changers-server
  name: game-changers-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: game-changers-server
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: mongodb
        - name: DB_NAME
          value: gameChangersStaging
        - name: ELASTICSEARCH_HOST
          value: elasticsearch:9200
        - name: ELASTICSEARCH_INDEX
          value: game_changers
        - name: FRONTEND_URL
          value: http://localhost:4200
        - name: JWT_SECRET
          value: yoursecret=D
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "4040"
        - name: REDISHOST
          value: redis
        image: game-changers-server
        name: game-changers-server
        ports:
        - containerPort: 4040
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app
          name: game-changers-server-claim0
      restartPolicy: Always
      volumes:
      - name: game-changers-server-claim0
        persistentVolumeClaim:
          claimName: game-changers-server-claim0
status: {}
